### ISSUE TITLE
Learn and enumerate

### ISSUE THREAD

**Issue by matlink** [cupslab/guess-calculator-framework#8]
Great job here.
I'm looking for a simple way to learn a PCFG from a dict file and then enumerate candidates according to this PCFG.
I've looked into the USAGE.md except that it's very confusing to me, I can't figure out how that works, there are a lot of things over there ...
Is there any simple howto somewhere that explain the very basics of this framework?

**Comment by sarangak** [comment]
For your use case, it sounds like you might want: https://github.com/cupslab/guess-calculator-framework/blob/master/USAGE.md#4-generating-strings-directly-for-online-attack-modeling

The framework was written around doing experiments, but it also supports generating the strings directly.  As described in that section, once you train the PCFG and get a zip file with the grammar and scripts, you can run `parallel_gentable.pl` to generate strings.  Note the suggestion to use the `-A` flag, but you can also use the `-s` flag for much faster string generation albeit with possible duplicates.  If you run into any issues, let me know.

**Comment by sarangak** [comment]
> I'm looking for a simple way to learn a PCFG from a dict file and then enumerate candidates according to this PCFG.

You'll notice that the guess calculator framework can do a lot more than that.  We've found that once you get into lots of guesses, you pretty quickly run out of good strings.  This is why there is a complex configuration where we combine password lists, words from a Google corpus, etc.

I suggest starting with this config:
https://github.com/cupslab/guess-calculator-framework/blob/9a5ef6b95e62d66882c75a8a093ab8027fcf0503/example%20conditions/minibasic6_with_improvements/configs/minibasic6_with_improvements.dat

You can put your own password source in there and remove the Google corpus if you really don't want it.  You can also substitute words from Google with words from Wikipedia.

**Comment by matlink** [comment]
I've started with that king of configuration file, but the scripts are taking a very long time to proceed (more than 10 minutes for `create_training_and_test_corpora.pl` and more than 2 hours for `iterate_experiments.pl`).
`test_rockyou.txt_learn.txt` and `test_rockyou.txt_tests.txt` are both 7164921 words long.
Am I wrong somewhere? How can I speed the process up a bit?
```
# Use the same condition path as minibasic6 because all of the inputs are same
my $conditionpath = "example conditions/test_rockyou";
my $structures_tokenizer = "./character_class_tokenizer.py";  # In root framework directory

%TOP = ( 
  'name' => 'test_rockyou',
  'description' => 'test_rockyou',

  # PCFG learning parameters
  'tokenize_structures_method' => "$structures_tokenizer",
  'tokenize_structures_arguments' => '-d 0.01',
  'generate_unseen_terminals' => 1,

  # Quantizer parameters
  'totalquantlevels' => '5',
  'quantizeriters' => '30',  # Note that this is very low and should be increased to 1000 or so for real experiments

  # Evaluation control parameters
  'cutoffmin' => '1e-10',
  'cutoffmax' => '1e-10',

  # Training data
  'training_configuration' => {
    'structure sources' => [
      {   
        'name' => 'RockYou',
        'filename' => "/bases/test_rockyou.txt_learn.txt",
        'ID' => 'R',
        'weight' => 100 
      }   
    ]   
  },  

  # Test data
  'testing_configuration' => {
    'sources' => [
      {   
        'name' => 'RockYou100',
        'filename' => "/bases/test_rockyou.txt_tests.txt",
        'convert_from_single_column' => 1
      }   
    ]   
  }
);
```

**Comment by sarangak** [comment]
@matlink Two hours seems long for that size of input, but that might be right.  A couple questions:

1. The docs say the provided `minibasic6` test should take ~20 minutes.  How long does it take for you?

2. Does it produce the correct answer?  If so, note that you only need to generate the lookup table once.  See https://github.com/cupslab/guess-calculator-framework/blob/master/USAGE.md#step-4-looking-up-guess-numbers

There's a lot of on-disk operations, so the speed of your disks can affect the time.  If it is small enough to run on a RAM disk (like a `tmpfs` file system) it could speed it up a lot.
